### ISSUE TITLE
Error al intentar imprimir una factura

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/odoo-argentina#107]
Me aparece el siguiente error cuando intento imprimir una factura, algún problema con el partner.
![errorimprimir](https://cloud.githubusercontent.com/assets/9534646/14357659/f96a1b78-fcbf-11e5-9429-6ba91eff64a0.png)

Actualizo la información del issue.

> Después de revisar un rato, descubrí que todos los reportes llaman al campo iibb, ya que me tiraba el mismo error para todos los reportes de aeroo. Aparentemente se cambió el nombre del campo en la base de datos en las últimas actualizaciones y todos los reportes llaman a iibb.
> Espero que la info sea de ayuda para solucionarlo.

**Comment by luisguglielmi** [comment]
Es un proble en el campo de ingresos brutos de la compañia

**Comment by luisguglielmi** [comment]
es un error en el campo de ingresos brutos de la compañia

**Comment by adrianpaesani** [comment]
Listo, ya está solucionado con el último commit, ya se puede cerrar el issue. Gracias por el trabajo como siempre.
