### ISSUE TITLE
l10n_ar_padron_afip

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/odoo-argentina#108]
Me aparece el siguiente error cuando intento actualizar un cliente con el nuevo modulo de padrones, aparentemente intenta descargar un archivo, no se si es algún error que tengo yo, o todavía no está listo el módulo.
Adjunto unas capturas.

![error1](https://cloud.githubusercontent.com/assets/9534646/14528255/fe1e0232-0224-11e6-914e-85d4808f10b0.png)
![error2](https://cloud.githubusercontent.com/assets/9534646/14528257/013d9aa4-0225-11e6-95b2-6ceae2ae04dc.png)

Muchas gracias.

**Comment by jjscarafia** [comment]
Tenés que actualizar la imagen de docker de odoo-adhoc o tomar el repostiorio pyafipws de reingart de github

**Comment by pronexo-argentina** [comment]
Hola jjscarafia, a mi me pasa algo similar, andaba bien hace unos meses pero ahora me sale un error al intentar actualizar desde afip a un cliente
![captura de pantalla 2017-12-10 03 51 04](https://user-images.githubusercontent.com/11078121/33802756-52a569aa-dd87-11e7-8e1a-dfc5b3a82484.png)


**Y al intentar crear uno nuevo**
![captura de pantalla 2017-12-10 03 52 48](https://user-images.githubusercontent.com/11078121/33802773-9dcaad3c-dd87-11e7-9092-a1d9a794bc56.png)

![captura de pantalla 2017-12-10 03 53 08](https://user-images.githubusercontent.com/11078121/33802774-a79f46ec-dd87-11e7-8b23-6b93a43948fc.png)
