### ISSUE TITLE
Factura Electronica - Mostrar el request XML en caso de error o por lo menos loguearlo por sistema

### ISSUE THREAD

**Issue by mgscreativa** [ingadhoc/odoo-argentina#118]
Hola, al intentar validar una factura en modo homologacion el odoo me tira un error, seguramente es algo que tenga que ver con mi condicion de monotributista, puse una pregunta aca https://www.odooargentina.com/forum/ayuda-1/question/imposible-lograr-validacion-de-factura-en-homologacion-1233

Al margen de la pregunta, seria bueno que el modulo de afip FE tire el request XML ya sea por pantalla o que lo logee por sistema, asi se puede ver que pasa y si se puede solucionar.

> **Mostrar el request XML en caso de error o por lo menos loguearlo por sistema**
> 
> _Version affectada:_
> - 8.0
> 
> _Pasos para reproducir:_
> 1. Instalar Odoo avanzado con docker
> 2. Crear DB sin datos de ejemplo
> 3. Instalar localizacion argentina con plan de cuentas para Monotributistas
> 4. Habilitar FE
> 5. Editar el partner para agregar CUIT
> 6. Crear diarios
> 7. Crear certificado FE homologacion
> 8. Crear factura y validar
> 
> _Lo que pasa actualmente:_
> - Falla con el siguiente error, sin informacion detallada del request XML: AFIP Validation Error. soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1659). ---> Input string was not in a correct format.
> 
> _Lo que debe pasar:_
> - Mostrar el request XML en caso de error o por lo menos loguearlo por sistema
> 
> _Analisis profundo:_
> - Quizas en un problema con el impuesto por producto para monotributistas, yo cree uno nuevo que se llama "Responsable Monotributo" quue no agrega nada de impuesto, quizas no sea la forma correcta de implementarlo, pero si no pongo nada en impuesto, me tira otro error, referente a que falta el impuesto ????
> - Es posible que la implementacion de FE de ustewdes no contemple este caso para monotributistas?

**Comment by jjscarafia** [comment]
Buenas, muchas gracias por tan detallada incidencia y los pr.
1. El request queda almacenado en la factura pero solo en casos de éxito, esto es así porque cuando arojas un mensaje de excepción con odoo se hace un roll back y no se almacenan los datos en bd, tenemos anotado para mejorarlo en v9.
2. Si, no es compatible con monotributistas, tenemos agendado cambiar esto por diversos motivos. Según entendemos el iva no corresponde de las tablas de afip sería el impuesto justo para monotributistas.

El cambio no es trivial y lo vamos a hacer recién par la v9 en la cual estamos empezando a trabajar y esperamos tener lista para fin de año.

**Comment by mgscreativa** [comment]
Ok, sabes que en el módulo de FE agregue una línea de _logguer luego de if msg: para loguear el request al log del sistema y no me logueo nada, es normal eso? Como se podría hacer?

Al margen, me gustaría poder aportar ayuda si necesitan algo para el tema monotributistas.

**Comment by jjscarafia** [comment]
Mm, raro que no te muestre nada. Super bienvenido en colaborar, definimos
hace poco empezar a congelar las versiones de ser posible.
Dentro de poco vas a ver que se van a mover los branch de la 9, podes
aportar con testing, opiniones, PR, traducciones o lo que quieras.
Saludos,
Juan

**Comment by mgscreativa** [comment]
Al pelo!, hoy mas tarde te mando un snippet de lo quetrate de hacer para loguear el request XML y no me funciono a ver si me podes dar tu opinion. Seguramente no funciono debido a mi total desconocimiento del lenguaje jajaja

**Comment by mgscreativa** [comment]
Hola @jjscarafia!, fijate en la línea 455, esto lo agregue en el archivo l10n_ar_afipws_fe/models/invoice.py https://gist.github.com/mgscreativa/b4f32c43865148071c96a1ded3de048a

Esperaba que con eso me apareciera en el log el request completo, sin embargo no aparece...

**Comment by jjscarafia** [comment]
ya está mejorado en v13
