### ISSUE TITLE
Provincias Duplicadas

### ISSUE THREAD

**Issue by mgscreativa** [ingadhoc/odoo-argentina#119]
Hola, he instalado la localización siguiendo los pasos de docker avanzado, y cree una DB con datos de ejemplo.

Al instalar la localizacion desde los modulos, si clickeo la opcion **Provincias Argentinas** estas se duplican.

Aparentemente al instalar los datos de ejemplo, las provincias ya se instalan, quizas habría que sacar los datos de ahi para que al clickear **Provincias Argentinas** no se dupliquen.

Esto se soluciona fácilmente si se destilda la opcion **Provincias Argentinas** en la configuracion de la localizacion argentina

**Comment by jjscarafia** [comment]
Bárbaro, esto se solucionaría si usamos los mismos ids, anoto como para mejora para v9

**Comment by jjscarafia** [comment]
Solucionado en la v9
