### ISSUE TITLE
odoo-argentina/l10n_ar_afipws_fe/i18n/es.po

### ISSUE THREAD

**Issue by nickoarg** [ingadhoc/odoo-argentina#136]
Texto en linea 426 dice: Mo**en**das en lugar de Monedas

l10n_ar_currency_update/i18n/es.po 
linea 24 TAZA es TASA
Linea 30 TAZA es TASA

l10n_ar_afipws_fe/i18n/es.po 
Linea 105 es TASA
Linea 111 es TASA

l10n_ar_invoice/i18n/es.po 
Linea 570 es TASA
Linea 575 es TASA

Gracias!!

**Comment by jjscarafia** [comment]
Gracias Nico, podrás hacer un PR o arreglarlo en transifex?
