### ISSUE TITLE
FIX module conflicts

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#175]
Non installable module l10n_ar_currency_update due to conflict on dependencies 

Impacted versions:
9.0

Steps to reproduce:
1. Install module l10n_ar_currency_update

Current behavior:
l10n_ar_currency_update depends from currency_rate_update module forked from OCA to /ingadhoc/account-financial-tools but doesn't exist, but it does exist adhoc-dev/oca-account-financial-tools but doest has 9.0 branch

Error context:
Odoo warning:
Intenta instalar el módulo 'l10n_ar_currency_update' que depende del módulo 'currency_rate_update'.
Este último módulo no está disponible en su sistema.

Expected behavior:
Success install of l10n_ar_currency_update

Proposed solution:
Fork an OCA branch 9.0 module from account-financial-tools named "/ingadhoc/oca-account-financial-tools"

**Comment by jjscarafia** [comment]
El módulo ya está disponible en la oca https://github.com/OCA/account-financial-tools/tree/9.0/currency_rate_update
