### ISSUE TITLE
Actividad económica AFIP

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#178]
Juan
Adjunto el csv que ya está testeado en v9 y anda perfecto para que lo incluyas en la localización.
Saludos!
[ACTIVIDADES_ECONOMICAS.txt](https://github.com/ingadhoc/odoo-argentina/files/758670/ACTIVIDADES_ECONOMICAS.txt)

**Comment by jjscarafia** [comment]
Seba, las actividades se sincronizan con los botones de contabilidad/configuración y ahora también, al instalar el módulo, se sincronizan y crean automáticamente (Actividades, impuestos y demás). Alguna razón por la que sería mejor ya incluirlas?

**Comment by SBollatti** [comment]
No Juan
Desconocia la opción que mencionas en la Configuracion del módulo
Contabilidad.
Gracias!
