### ISSUE TITLE
v9 l10n_ar sale price currency update

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#179]
Juan
¿Hay alguna forma que se actualice automáticamente el precio del producto definido en otra moneda como lo hacia v8?

Hoy está de esta manera:

Planned Price based on
"Cambio de moneda"
Precio Planeado en la Moneda
"USD 1,064"

Precio Plenado
$ 16,86

Precio de venta (debo verificary actualizarlo manualmente en cada operacion si coincide)
$ 16,920

Saludos!

**Comment by jjscarafia** [comment]
Podes actualizarlo seleccionando en la vista lista y correr la acción correspondiente. O activando el cron que se crea con el módulo pero que queda desactivado.
