### ISSUE TITLE
Recibo de Cliente.

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#188]
Juan
En en último pull de v9 todos los módulos de Adhoc funcionando con contabilidad argentina, me encontré que en Recibos de Cliente desapareció la opción "Efectivo" y queda el campo en blanco sin poder llenarlo.
¿podes tener una instancia en el runbot2 para RI de sociedades con todas los módulos l10n_ar instalados en el cuál sirva para replicar errores, así te es mas facil a vos y al resto de la comunidad?
Al intentar guardar sin validar me encuentro con lo siguiente:
"No puede hacer esta modificación en un asiento de diario publicado, sólo puede cambiar algunos campos no lelgales. Tiene que revertir el asiento de diario para cancelarlo.
Nombre movimiento (id): FV/2017/0008 (55)."
Saludos
Seba

**Comment by jjscarafia** [comment]
Buenas Seba, fijate si podes usar este runbot http://runbot2.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-odoo-argentina-git-6

**Comment by SBollatti** [comment]
Reproducido Juan
Este es el runbot:
[http://00240-9-0-ec2fbd.runbot2.adhoc.com.ar/web/login](url)
![issue1](https://cloud.githubusercontent.com/assets/11006126/25775440/93e47bca-327b-11e7-8b31-235c1a0d24d4.png)
![issue2](https://cloud.githubusercontent.com/assets/11006126/25775462/e77f0b60-327b-11e7-959e-23cd631a40f2.png)
Saludos y buen finde!

**Comment by jjscarafia** [comment]
Ese problema se debe a una incompatibilidad que se generó con odoo en un pr de odoo de hace un par de meses. Se habló en este hilo https://groups.google.com/forum/#!topic/odoo-argentina/mqmEtRbHN1c

Por ahora no le pusimos energía para resolverlo porque estamos sobre la enterprise y no nos afectó, pero es algo que tengo pendiente de ver. Matias Cerutti iba a trabajar en eso tmb. Fijate si algo del hilo te aporta algo..

**Comment by mcerutti** [comment]
Hola Seba, mira, por ahora la solucion rapida es que hagas un downgrade a un release de principios de marzo, y con eso te van a funcionar los modulos, porque todavia no pude solucionar el problema de los dominios. Estoy trabajando en eso.

**Comment by SBollatti** [comment]
Matias.
No logro dar con el comando de github para hacer el downgrade. En el foro
de Odoo-Argentina publiqué uno pero no funciona. La instancia corre en
virtualenv.
Saludos

**Comment by jjscarafia** [comment]
Dejo constancia de los dos links que @mcerutti mandó en el grupo de la localización:
- [workaround](https://github.com/odoo/odoo/issues/16072
)
- [error a partir del siguiente commit](https://github.com/odoo/odoo/commit/bc0313791cdfc363b889291df82ab779e864e7db)

**Comment by jjscarafia** [comment]
Bueno, por fin ya estaría corregido este problema.
Cerrado con este commit https://github.com/ingadhoc/odoo-argentina/commit/e0d6476e51f566059984b01c90b3c01780441596

**Comment by SBollatti** [comment]
Buenisimo!
