### ISSUE TITLE
Traducción Notas de Crédito

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#192]
Juan
¿puedo cambiar en Transifex la traducción de las Facturas Rectificativas a Notas de Crédito?
![image](https://cloud.githubusercontent.com/assets/11006126/26106730/317dcf14-3a1d-11e7-856c-ca1a6ce892da.png)
Cuando lo leí por primera vez a la primer opción, me dio a pensar que hacia una Factura nuevamente y la Factura a cancelar con la Nota de Crédito quedaba pendiente con los saldos de IVA en contra.

En la opción que decía Modificar que hacia todo el "combo" era justo lo que estaba necesitando y "error" (probado en el Runbot2 de Adhoc).

...luego me animé por la primer opción y me dí cuenta que estaba confusa la expresión de la traducción. Por lo menos que para el Spanish (AR) que sea entendible para los Argentinos.
Saludos!
Seba

**Comment by jjscarafia** [comment]
Mmm. esto habría que analizarlo bien porque el término aparece en varios lugares, además la traducción es_AR parece desaparecer en v10, voy a hablar de esto en los odoo experience 2017 y vemos cual es la mejora manera..
