### ISSUE TITLE
Datos Opcionales de factura electrónica

### ISSUE THREAD

**Issue by angra1982** [ingadhoc/odoo-argentina#216]
Hola, esto no es un issue pero realmente no encuentro de que forma agregar datos opcionales a una factura electrónica desde odoo. hay algunas facturas particularmente para alquileres que afip exige agregar algunos parámetros que llaman opcionales. pyafipws permite esto con la función AgregarOpcional pero no veo de que forma hacerlo en el modulo para odoo. 
Gracias

**Comment by jjscarafia** [comment]
esta funcionalidad no está implementada, llegado el caso creo que debería implementarse la mejora de soporte para alquileres
