### ISSUE TITLE
Fallo en la instalación por virtualenv

### ISSUE THREAD

**Issue by alener** [ingadhoc/odoo-argentina#223]
He seguido las insttrcciones de instalación provistas en: https://www.odooargentina.com/blog/blog-1/post/instalando-odoo-utilizando-virtualenv-35
Al finalizar la instalacion salió un mensaje que decía:./odoo-dev.sh: line 89: odoo.py: command not found

Luego al ejecutar odoo.py -c odoo.conf en la terminal sale el mensaje:  odoo.py: command not found

Está la opción de hacerlo por docker pero de todas maneras quería reportar este bug

Estoy usando Ubuntu17.10

**Comment by SBollatti** [comment]
Alejandro.
Me parece que ejecutaste el odoo.py -c odoo.conf -s fuera del ambiente por
lo que no lo encuentra. Por otro lado no olvides una vez hecho git clone
https...odoo.git de entrar en la carpeta y ejecutar siempre desde dentro
del ambiente pyhton setup.py install para instalar la instancia (también si
no hiciste este paso puede darte el mismo error)
Saludos
Seba

**Comment by alener** [comment]
Para que quede mas claro:
(90) alejandro@endland:~/odoo/90$ odoo.py -c odoo.conf -s
odoo.py: command not found
(90) alejandro@endland:~/odoo/90$ python odoo.py -c odoo.conf -s
python: can't open file 'odoo.py': [Errno 2] No such file or directory
(90) alejandro@endland:~/odoo/90$ ls
bin      lib                   odoo       pip-selfcheck.json
include  oca_dependencies.txt  odoo.conf  sources
(90) alejandro@endland:~/odoo/90$ ls odoo
addons           doc          odoo.py         openerp-wsgi.py   setup.cfg
CONTRIBUTING.md  LICENSE      openerp         README.md         setup.py
COPYRIGHT        Makefile     openerp-gevent  requirements.txt
debian           MANIFEST.in  openerp-server  setup
(90) alejandro@endland:~/odoo/90$ cd odoo
(90) alejandro@endland:~/odoo/90/odoo$ python odoo.py -c odoo.conf -s
  File "odoo.py", line 31
    print "odoo:" + f % l
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "odoo:" + f % l)?

**Comment by jjscarafia** [comment]
Por casualidad, no lo estás usando para versión 10 u 11? No lo probamos para esas versiones. En 11 de seguro que no funciona así porque en vez de odoo.py debe ser odoo (y no estoy seguro si algún que otro cambio).
Cierro igual el issue ya que no es una incidencia de localización argentina si no que tiene que ver con instalación de odoo.
Saludos
