### ISSUE TITLE
Factura desde contabilidad no descuenta stock

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#27]
Impacted versions:
8.0 

Steps to reproduce:
Base de datos limpia sin ejemplos con la localización de adhoc instalada y actualizada al 09/05/2015 branch 8.0

Step 1.
Crear un producto “lapices, precio 10 Seleccionar - Tipo de producto almacenable

Step 2.
Crear un cliente responsable inscrito.
Crear un proveedor Responsable inscripto.

Step 3.
Crear una orden de compra, ingresar 100 unidades de producto

Step 4.
Ingresar a Contabilidad – Facturas de Cliente
Crear factura por 10 lapices 
validar

Step5.
Ingresar a Depósito  - productos

Behavior
verificar el stock del producto 
Al facturar a través de contabilidad – Facturas de clientes el stock no se reduce, queda igual que antes de efectuar la venta.

Step6.
Ir a Ventas - Presupuestos
Facturar 20 unidades de lapices y seguir todos los pasos incluidos la entrega.
Al facturar a través de ventas siguiendo la secuencia directamente desde presupuestos hasta el final, utilizando los remitos si se descuenta el stock.

Expected Behavior
El stock debería reducir en 10 unidades desde contabilidad si la venta se hace directamente sin remito.

Note:
Se probó en 2 instalaciones diferentes

**Comment by martinfpas** [comment]
Pasa lo mismo en la version 7. La única solución sin tocar codigo, es hacer una orden de venta antes y después sobre esta crear la factura.

**Comment by jjscarafia** [comment]
Ese es el comportamiento por defecto de odoo. Las facturas afectan las
cuentas, los remitos afectan el stock. Una factura por i sola no va afectar
el stock. Cierro la incidencia. ·#close
