### ISSUE TITLE
Report modification request

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#30]
Con el Report de Solicitud de Compras de la localización de Uds tengo problemas con mis proveedores que "les impongo" el importe en la columna de "Precio de Lista" y genero alguna aspereza no deseada y sin dudar si vuelvo a reincidir enviando otro.
¿Es mucho pedir que corrijan esto?
Cuando se pide precio que sea sin precio y cuando se compre que diga Orden de Compra y debe incluir el precio.
Este issue deriva de un email a Gonzalo Ruzafa del 18/5 el cual pide que genere un issue.

**Comment by jjscarafia** [comment]
Ok, cuando tengamos tiempo lo vamos a atacar. Gracias por registrar el
issue!

**Comment by SBollatti** [comment]
Juan
Agrego para esta mejora lo siguiente:
- En el cuerpo del email, cuando envia la "Solicitud de Presupuesto" lo hace con el cuerpo de la Orden de Compra y queda muy desprolijo.

¿como puedo ayudar para corregir este reporte y lo consiguiente para lograr la funcionalidad completa de la Compras?

**Comment by jjscarafia** [comment]
Buenas Sebastian, la verdad es que si el mail se manda como orden de compra debe ser un bug de odoo, no recuerdo que nosotros cambiemos que mail se manda. Igualmente deberías poder cambiar las plantillas si así lo deseas...

**Comment by SBollatti** [comment]
Ok, hago una base limpia y pruebo, quizás esta parte del issue tenga que ir para Odoo y no Adhoc

**Comment by jjscarafia** [comment]
Cerrado por viejo
