### ISSUE TITLE
Aplicación en Odoo 12

### ISSUE THREAD

**Issue by lugezz** [ingadhoc/odoo-argentina#317]
Cómo se implementa estas funcionalidades en Odoo 12? Gracias!

**Comment by sotolucas** [comment]
Hola Eugenio.
Deberías clonar el repositorio en algún path de tu preferencia para los módulos custom:
`sudo git clone https://github.com/ingadhoc/odoo-argentina/ -b 12.0`

Es importante:
- Agregar este repositorio en tu odoo.conf (parámetro addons_path).
- Instalar dependecias externas (Librerías de Python) con:
`sudo pip3 install -r requirements.txt`
- Instalar repositorios necesarios (que se encuentran dentro del archivo oca-dependencies.txt).

Algunas consideraciones:
- Es posible que el paquete M2Crypto debas compilarlo (por favor referirte a la documentación del desarrollador).
- A su vez los repositorios necesarios también requieren de otros repositorios.
- Estas indicaciones podrían variar de acuerdo a tu sistema operativo.
- Podrías buscar algún script o imagen de Docker que facilite el despliegue.

Saludos.
