### ISSUE TITLE
Factura Electronica - Error al validar rectificativa

### ISSUE THREAD

**Issue by mariodmoreno** [ingadhoc/odoo-argentina#342]
> **Error al validar rectificativa(nota de crédito) en wsfe**
>
> *Versiones afectadas*
> 
>  - 11.0
> 
> *Pasos para reproducir:*
> 
>  1. En un ambiente producción o en homologacion con un diario de ventas de tipo electrónico wsfev1 generar una factura y validar.
>  2. Utilizar el wizard de emitir rectificativa.
>  3. Seleccionar la primera opción y rellenar los campos, seleccionar nota de crédito.
>  4. Validar
> 
> *Lo que pasa actualmente:*
> 
>  - /l10n_ar_afipws_fe/models/invoice.py", line 680, in do_pyafipws_request_ca
afip_ws != 'wsmtxca' and CbteAsoc.date_invoice.replace("-", "") or CbteAsoc.date_invoice,
TypeError: AgregarCmpAsoc() takes from 1 to 5 positional arguments but 6 were given
> 
> *Lo que debe pasar:*
> 
>  - Que se valide la Nota de Credito 
>
> *Analisis profunda:*
>
>  - Creo que es un problema con las diferentes versiones de pyafipws. 
>  - Si observamos en la version master correspondiente a python2.x en https://github.com/reingart/pyafipws/blob/master/wsfev1.py#L171 tenemos declarada la funcion que estamos invocando en https://github.com/ingadhoc/odoo-argentina/blob/fcd78d7388c1c7b77e1b45edbf63202836156c92/l10n_ar_afipws_fe/models/invoice.py#L675 las cuales poseen la misma cantidad de argumentos. 
>  - Sin embargo en la rama que utilizamos para python3 el argumento fecha no esta presente. https://github.com/reingart/pyafipws/blob/51438f6368fc949227292c1406561441e0f47226/wsfev1.py#L173.
>  - No se si esto deberia tambien disparar un issue en el repositorio de pyafipws ya que en teoria wsfe incluye fecha en comprobantes asociados.

**Comment by marianoadangelo** [comment]
actualiza la version de pyafipsws utiliza git+
https://github.com/ingadhoc/pyafipws@py3k .
Hoy me paso lo mismo y actualizando no tuve problemas

**Comment by mariodmoreno** [comment]
@marianoadangelo Muchas gracias! si lo hice ayer y no me había funcionado. Así que ahora que me lo decís desinstale pyafips y lo volví a instalar y parece funcionar. 
Sin embargo ayer me llamo la atención que solo esa opción del wizard de rectificativa me de error. Aparentemente en las demás no se están enviando los comprobantes asociados.
Alguien sabría si esto es correcto?
