### ISSUE TITLE
Calculo de retenciones no se conecta con ARBA

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/odoo-argentina#361]
> **No se conecta con ARBA**
>
> *Versiones affectada:*
> 
>  - 9.0 y 11.0
> 
> *Pasos para reproducir:*
> 
>  1. cargar un pago a proveedor
>  2. oprimir el boton CALCULAR RETENCIONES
> 
> *Lo que pasa actualmente:*
> 
>  - sale un cartel diciendo <![CDATA[El Padron consultado no se encuentra publicado.]]/> Error DATO:6
> 
> *Lo que debe pasar:*
> 
>  - Deberia bajar la alicuota del partner y calcular las retenciones
>
> *Analisis profunda:*
>
>  - Yo creo que la causa raiz es o no esta funcionando el ws de ARBA o algo le cambiaron.
>  - Me lo reportaron en v9 y lo verifique tambien en v11

**Comment by sotolucas** [comment]
Hola Jorge. Gracias por reportar el issue.
Sí, estamos al tanto del inconveniente y es de ARBA. Si intentás descargar el padrón desde el sitio web, vas a ver que no se encuentra publicado.
Saludos.

**Comment by jobiols** [comment]
ok gracias por responder, esperaremos a que lo arreglen ellos entonces.
