### ISSUE TITLE
[12.0] Error con sincronización de numeración de facturas

### ISSUE THREAD

**Issue by 3DOeste** [ingadhoc/odoo-argentina#371]
El chequeo de la numeración de documentos (facturas, etc) con respecto a AFIP está OK, pero al tratar de sincronizarlos, no lo hace, quedan iguales, y si manualmente se le pone el número, asume que otros documentos también llevan ese número.

Ej:
AFIP, Factura A, próximo número 3, resto de documentos 1

Odoo, Factura A, próximo número 3, automáticamente asume que las notas de crédito, débito y facturas mipyme van por el mismo número.

Probé con secuencia propia y misma secuencia de factura y el resultado es el mismo.

**Comment by sotolucas** [comment]
Hola @3DOeste , gracias por reportar el issue!

**Comment by 3DOeste** [comment]
El problema está en que no se crearon automáticamente las secuencias, sólo crea la de FACTURAS A y usa para las ND, NC y facturas mipyme la misma secuencia de FACTURAS A.
No se si es un bug o sólo un problema de configuración mio.
Tendría que crear una nueva DB y ver si pasa lo mismo.

**Comment by sotolucas** [comment]
Hola @3DOeste ! Quedamos a la espera de tu testing.
Muchas gracias.
