### ISSUE TITLE
[12.0] Se requiere n° de CBU para FACTURA DE CRÉDITO ELECTRÓNICA MiPyME (FCE) A

### ISSUE THREAD

**Issue by FedericoLaTorre** [ingadhoc/odoo-argentina#377]
Al tratar de validar una FCE A se necesita un CBU

AFIP Validation Error. 10165: El contenido del campo VALOR para Opcionales de Facturas de Credito ID=2101. El valor correcto es un CBU valido, numerico de 22 caracteres numericos.

**Comment by jjscarafia** [comment]
Buenas Federico, lo que tenés que hacer es tener una cuenta bancaria para tu compania con cbu configurado y setearla en la pestaña otra info de la factura (si ya está creada se te debería llevar por defecto).
Saludos!

**Comment by FedericoLaTorre** [comment]
Muchas gracias, me estaba volviendo loco, y eran muchos items y se cerraba la sesión en la página de AFIP.

**Comment by DaianaRomera** [comment]
Me sumo a este error. Cómo puedo cargar la CBU a la cuenta bancaria y setearla en la pestaña de la factura?
