### ISSUE TITLE
[V12] Error with multi-localization

### ISSUE THREAD

**Issue by luistorresm** [ingadhoc/odoo-argentina#381]
> **Soportar multiples localizaciones**
>
> *Version affectada:*
> 
>  - 12.0
> 
> *Pasos para reproducir:*
> 
>  1. Instalar l10n_ar_partner
> 2. Instalar otra localización, por ejemplo México 
> 
> *Lo que pasa actualmente:*
> 
>  - En México el VAT no es calculado, y el campo para capturarlo esta oculto.
> 
> *Lo que debe pasar:*
> 
>  - Si el país de mi partner es México, yo debo poder capturarlo
>
> *Analisis profunda:*
>
>  - Si en Argentina el campo es calculado, podemos hacer que el campo sea oculto solo si los valores para el llenado de este están llenos

**Comment by luistorresm** [comment]
@jjscarafia 

¿Qué te parece este ticket? Yo puedo proponer la mejora, pero antes quisiera saber tu punto de vista.

Saludos

**Comment by jjscarafia** [comment]
Quedamos en que se hacia por personalizacion
