### ISSUE TITLE
[12.0] [Imp] Soporte para multicompañía

### ISSUE THREAD

**Issue by FedericoLaTorre** [ingadhoc/odoo-argentina#405]
Simplemente una sugerencia, estaría bueno si al momento de sacar el reporte de IVA ventas / compras / CITI, se puedan elegir los diarios de otras compañías, en el caso que sean varias marcas bajo un mismo CUIT.

**Comment by jjscarafia** [comment]
Buenas @FedericoLaTorre , gracias por la sugerencia. Sinceramente nunca vi una implementación donde se usen varias compañías para la misma compañía fiscal, entiendo que te referís a eso, no?

**Comment by FedericoLaTorre** [comment]
Si, exactamente, bajo un mismo CUIT hay dos actividades muy diferentes y está implementado como multicompañía, y la verdad que funciona muy bien, pero noté eso al tratar de sacar el reporte.

**Comment by FedericoLaTorre** [comment]
Me faltó agregar que si bien tienen el mismo cuit, cada compañía factura con un punto de venta distinto, para que sea fácil identificar a que actividad pertenece cada factura en AFIP. Y por supuesto en odoo tienen diarios separados.

**Comment by jjscarafia** [comment]
Perfecto @FedericoLaTorre , entendido.
En el módulo actual por ahí es un poco complicado porque está el campo "company_id", que es verdad podría convertirse en un m2m.
Por ahí este approach sería más "lindo" si se hace en v13 sobre el libro iva / txt de la versión enterprise de odoo ya que los reportes de odoo están más preparados para multicompañía (tanto a nivel técnico como de usabilidad).

Cuestión, dejo el ticket abierto, por nuestro lado por ahora no atacaríamos esta mejora hasta que no la necesitemos para algún cliente.

Saludos!
