### ISSUE TITLE
error modulo l10n_ar_account_vat_ledger_city

### ISSUE THREAD

**Issue by gbhadolfo** [ingadhoc/odoo-argentina#42]
Hola, instalé el módulo l10n_ar_account_vat_ledger_city y obtengo este error al querer generar el reporte:

l10n_ar_account_vat_ledger_city/models/account_vat_report.py", line 178, in get_REGINFO_CV_CBTE
    self.invoice_ids.check_argentinian_invoice_taxes()
AttributeError: 'account.invoice' object has no attribute 'check_argentinian_invoice_taxes'

Ojala puedan solucionarlo. gracias y saludos.
Adolfo

**Comment by jjscarafia** [comment]
Sigue pasando este error? Reiniciaste el servicio luego de actualizar?
