### ISSUE TITLE
Modulo l10n_ar_wittholding requiere libreria pyafipws

### ISSUE THREAD

**Issue by aparragithub** [ingadhoc/odoo-argentina#423]
Al intentar instalar el modulo l10n_ar_withholding requiere de la libreria pyafipws para Odoo V13.

Es necesario contar con esta librería para poder poder instalar el modulo, o aun se están realizando cambios en este modulo para que funcione sin el uso de esta libreria?

![Capture 2020-06-04 at 14 34 08](https://user-images.githubusercontent.com/607418/83802531-8cfa8e00-a670-11ea-98df-32f16a473593.png)

**Comment by sotolucas** [comment]
Hola @aparragithub !
No en la versión community. 
Se seguirá usando PyAFIPWS.
Saludos y gracias por tu consulta.

**Comment by jjscarafia** [comment]
@aparragithub por ahora la conexión a arba es mediante pyafipws. Es por eso que ese módulo requiere PyAFIPWS
el requirements muestra bien las dependencias del repo https://github.com/ingadhoc/odoo-argentina/blob/13.0/requirements.txt
