### ISSUE TITLE
No se ven los campos de "Periodos Fiscales" 13.0

### ISSUE THREAD

**Issue by martin994** [ingadhoc/odoo-argentina#443]
No se ven los campos de "Periodos Fiscales" en Ajustes->Contabilidad
Versión afectada:13
> 
> *Pasos para reproducir:*
> 
>  1. Simplemente voy con el administrador(con o sin debbuger) a este formulario, y se visualiza la sección "Periodos Fiscales" sin opciones dentro.
> 
> *Lo que debe pasar: Supongo que debería mostrar campos. 
> 
>
> *Análisis profunda:*
>
>  - Creo que hay alguna configuración de usuario (de permisos) que me este afectando.
>  - Supongo que me puede llegar a faltar alguna librería de python, pero en el log no se observa ninguno error.
![image](https://user-images.githubusercontent.com/19803400/95218171-612c1800-07ca-11eb-939f-c7969e4a3e95.png)

**Comment by jjscarafia** [comment]
Esto no parece tener que ver con este repo ni la localización argentina, parece algo de odoo
