### ISSUE TITLE
Posible error

### ISSUE THREAD

**Issue by SBollatti** [ingadhoc/odoo-argentina#45]
Estimados
Luego de actualizar la localización e instalar/desinstalar varios módulos me encontré con un detalle que quizás se pueda evitar.
![aca](https://cloud.githubusercontent.com/assets/11006126/9227807/cce3e4d4-40eb-11e5-9d34-448bf5cb1aa1.jpg)

Se perdieron los datos de los 3 campos en círculo rojo que dan el "Tipo", "Nº" y "Responsabilidad". El número no se perdió ya que está en la pestaña de "Contabilidad" pero sí el "Tipo" y "Responsabilidad" que al momento de presupuestar o facturar aparece la necesidad de tener esto correctamente cargado.

Ojalá puedan replicarlo a este issue.

Saludos!

Seba

**Comment by jjscarafia** [comment]
El tema es que al desintalar modulos se borra la data que esos modulso instalan. Lo ideal es no desinstalar nada que tenga datos que vos querés. Se pueden poner script para que no se borren, pero nunca tuvimos que desinstalar l10n_ar_invoice y por eso tampoco lo hicimos.
Slaudos
