### ISSUE TITLE
AFIP Validation Error. 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.

### ISSUE THREAD

**Issue by emavarela** [ingadhoc/odoo-argentina#493]
> **AFIP Validation Error. 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.**
>
> *Version affectada:*
> 
>  - 12.0
> 
> *Pasos para reproducir:*
> 
>  1. Crear un diario de venta electrónica que use Webserive de AFIP Mercado interno -sin detalle- RG2485 (WSFEv1).
>  2. Usando este diario crear una factura para un cliente responsable inscripto ( Factura A ) con un artículo cualquiera.
>  3. Luego, usando este mismo diario, crear una factura rectificativa por el mismo importe al mismo cliente.
>  4. Dar click en el botón Validar en HOMOLOGACION
>  5. Se exhibe el mensaje Odoo Server Error - Warning: AFIP Validation Error. 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
>
> *Lo que pasa actualmente:*
> 
>  - Se exhibe el mensaje Odoo Server Error - Warning: AFIP Validation Error. 10197: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
> 
> *Lo que debe pasar:*
> 
>  - Se valida la factura rectificativa
>
> *Analisis profunda:*
>
>  - Yo cre que la causa raiz es el reciente cambio en el servicio de la AFIP WSFEv1 que exige la información de los documentos asociados.
>  - Por lo que veo en /l10n_ar_afipws_fe/models/invoice.py el ampo CbteAsoc se agrega solo para wsfex u otros y no para wsfe
> - Adjunto los printscreen de la pantalla previo a dar click en Validar Homologacion
![factura rectificativa](https://user-images.githubusercontent.com/58047343/113612377-221a3a80-9626-11eb-8017-382d3a316e51.png)

**Comment by jobiols** [comment]
Esta mañana un cliente reportó el mismo error en odoo V8, esto pasa en produccion al validar una nota de credito.
Evidentemente algo cambio en AFIP

![screenshot-18 221 188 110-2021 04 05-16_16_29](https://user-images.githubusercontent.com/8525908/113615606-745d5a80-962a-11eb-9977-d28f86f9c47e.png)

**Comment by NahuelVarela** [comment]
Acabo de encontrar en este [grupo](https://groups.google.com/g/publicesvfoxpro/c/wJjKDD-7rdo) mas gente reportando el issue. Por lo que veo de [AFIP](https://www.afip.gob.ar/facturadecreditoelectronica/documentos/manual_desarrollador_COMPG_v2_18-beta1.pdf) este campo estaba como opcional desde el 18 de Junio, pero ahora lo implementaron como requerido.

**Comment by jjscarafia** [comment]
buenas @emavarela 
gracias por el detallado reporte.
por lo que veo en v12 se está pasando el comprobante asociado sin importar el ws https://github.com/ingadhoc/odoo-argentina/blob/12.0/l10n_ar_afipws_fe/models/invoice.py#L757
Ahora bien, es importante que se obtenga el comprobante asociado, esto suele ser a través del campo origen (aunque tmb intentamos adivinarlo desde la venta)
[Este](https://github.com/ingadhoc/odoo-argentina/blob/4d07d2adc91ce24bb68b6735150ba5e7082ab5d4/l10n_ar_afipws_fe/models/invoice.py#L253) es el método que intenta encontrar el comprobante asociado

Entiendo que estaría todo funcionando e implementado. Si queda algún error o se me pasó algo por alto por favor re-abrí el ticket.

Saludos!

**Comment by emavarela** [comment]
Para el resto de la comunidad dejo el comentario por si le sirve a alguien:

Si con este cambio de AFIP no pueden hacer notas de crédito desde el POS, instalen los módulos pos_order_mgmt y pos_order_return de OCA.

Luego en /pos_order_return/models/pos_order.py reemplazar:

'origin': self.returned_order_id.invoice_id.number,
            'name': _(
                'Return of %s' % self.returned_order_id.invoice_id.number),
            'refund_invoice_id': self.returned_order_id.invoice_id.id,

Por: 

'origin': **_self.returned_order_id.invoice_id.document_number_**,
            'name': _(
                'Return of %s' % **_self.returned_order_id.invoice_id.document_number_**),
            'refund_invoice_id': self.returned_order_id.invoice_id.id,

O bueno, hacen su propio módulo que herede el anterior y le hacen la modificación.

Luego dentro del POS, el proceso de devolución lo inician desde el icono del changuito en el POS:

![changuito](https://user-images.githubusercontent.com/58047343/113803626-529bca80-9733-11eb-952d-db5fc1631825.png)


Slds.

**Comment by santcosta** [comment]
Y que pasa cuando el comprobante asociado no se encuentra en el sistema ? Por ser una factura vieja . Salds
