### ISSUE TITLE
Localizacion Argentina + Odoo14 CE + Ubuntu Server 20.04

### ISSUE THREAD

**Issue by Maurix09** [ingadhoc/odoo-argentina#518]
> Instale todo sin mayores problemas, pero el código de barras de la factura electrónica no aparece.
>
> *Version affectada:*
> 
>  - Odoo 14.0 CE
>  - Ubuntu Server 20.04  
> 
> *Pasos para reproducir:*
> 
>  1. Genero la factura electrónica y recibo el código CAE
>  2. Guardo, hago clic en "Imprimir" y luego en "Factura electrónica"
>  3. Guardo PDF
> 
> *Lo que pasa actualmente:*
> 
>  - Sale la factura bien formateada, pero donde va el grafico del codigo de barras del CAE, aparece un recuadro en blanco.
>  - También habría que onsiderar el tema de que ahora piden código QR en las facturas
> 
>
> *Supongo:*
>
>  - Que debe faltar instalar algun componente en Ubuntu server 20.04 o modulo de Odoo14 que se encarga de presentar el grafico en la factura.

**Comment by sotolucas** [comment]
Hola! Si es 14.0 CE, entonces el issue debería ir en el repositorio odoo-argentina-ce, dado que este se bifurcó a partir de la 13.0 cuando la EE empezó a incluir facturación electrónica de forma nativa.

Este issue podría ayudarte https://github.com/ingadhoc/odoo-argentina-ce/issues/26

**Comment by jjscarafia** [comment]
buenas @Maurix09 
tal como dice lucas si es tema de factura electrónica deberías ver ese otro repo.
además agrego que esta localización no está desarrollada para v14. Esta versión de odoo decidmos saltearla y vamos a ir derecho a la v15.

saludos

gracias @sotolucas
