### ISSUE TITLE
Bug en observaciones para una factura (monto en letras)

### ISSUE THREAD

**Issue by dbareiro** [ingadhoc/odoo-argentina#58]
Hola, Juan. Buen día.

Estoy haciendo algunas pruebas con una base de datos con datos de prueba y encontré el siguiente error al convertir el importe a letras. También hay un pequeño detalle de un espacio faltante (Milciento). Pero creo que la parte más notoria es el "setenta y ocho" en vez de "setenta y nueve". Adjunto la porción correspondiente en el informe generado para que lo puedas ver.

![bugconversionmontoaletras](https://cloud.githubusercontent.com/assets/7597354/9831718/16e9e8c6-5938-11e5-98d9-a27d01e75d77.png)

Gracias anticipadas.

Saludos,
Daniel

**Comment by jjscarafia** [comment]
Bárbaro, gracias por reportar, confirmado. Es un asunto de redondeo
seguramente, el conversor a texto esta recibiendo ,78....

**Comment by dbareiro** [comment]
Hola, Juan. Buen día.

Genial. Gracias por confirmar.

Había pensado que podía ser un tema de redondeo, pero como no estaba seguro cómo se hace la conversión, no sabía si esa era la causa, ya que la parte decimal al aplicar el IVA es de dos decimales exactos y no tres.

Saludos,
Daniel

**Comment by jjscarafia** [comment]
Arreglado en https://github.com/ingadhoc/odoo-argentina/commit/fd0e18fb642c32f2571cd8f4eca9e44d3e30880d
Saludos!

**Comment by dbareiro** [comment]
Buenísimo, Juan!

Muchas gracias!

Saludos,
Daniel
