### ISSUE TITLE
Documentos no generados para punto de venta electrónico

### ISSUE THREAD

**Issue by dbareiro** [ingadhoc/odoo-argentina#59]
Hola, Juan.

Haciendo pruebas en Odoo con una base de datos de prueba, en el caso de un punto de venta electrónico no se genera para el libro de ventas los documentos de facturas de exportación y nota de débito por operaciones con el exterior. En este caso la compañía es un responsable inscripto, pero también noté un comportamiento similar en una base de datos donde la compañia estaba como monotributista. Esto solo sucede con un punto de venta electrónico; con un punto de venta manual no veo que pase. Supongo que una alternativa sería crear a mano estos documentos con las secuencias correspondientes.

Si podés revisar esto para ver si lo podés replicar, sería genial. Adjunto unas capturas de pantalla para graficarlo.

![poselectroico_documentosventa](https://cloud.githubusercontent.com/assets/7597354/9831797/414fd6ae-593b-11e5-993d-cdd820842620.png)
![posmanual_documentosventa](https://cloud.githubusercontent.com/assets/7597354/9831799/47934398-593b-11e5-9edb-8b32f8715ed1.png)

Gracias anticipadas.

Saludos,
Daniel

**Comment by jjscarafia** [comment]
El tema es que para factura de exportación electronica se usa otro
webservice y no queda otra que generar otro punto de venta, por eso es así.
#close
Saludos,
Juan

**Comment by dbareiro** [comment]
Hola, Juan.

> El tema es que para factura de exportación electronica se usa otro webservice y no queda otra 
> que generar otro punto de venta, por eso es así.

Ah, bien! Gracias por la aclaración.

Solo para confirmar, ¿este webservice de exportación incluye tanto facturas de exportación como nota de débito por operaciones con el exterior?

Saludos,
Daniel

**Comment by jjscarafia** [comment]
Si, tan cual, debería ser así

**Comment by dbareiro** [comment]
Perfecto! Gracias por la pronta respuesta!

Saludos,
Daniel
