### ISSUE TITLE
Invoice subtotal (...) is different from invoice base vat amount

### ISSUE THREAD

**Issue by dbareiro** [ingadhoc/odoo-argentina#61]
Hola, Juan. Buenas tardes.

Haciendo pruebas con una base de datos con datos demo, encontré el siguiente comportamiento. Al facturar desde una empresa responsable inscripta, si quiero validar una factura B para Agrolait, a quien en este caso configuré como consumidor final, obtengo el siguiente error:

```
Invoice ID: 13
Invoice subtotal (1799.00) is different from invoice base vat amount (0.00) 
```

En el caso de intentar validar una factura A a un responsable inscripto, no hay problema. ¿Esto sería un bug?

![errorvat_facturab_1](https://cloud.githubusercontent.com/assets/7597354/9884262/3f79804c-5bb5-11e5-8884-e47f66653cdc.png)
![errorvat_facturab_2](https://cloud.githubusercontent.com/assets/7597354/9884263/3f9dc394-5bb5-11e5-97be-33ff4f80154f.png)

Gracias anticipadas.

Saludos,
Daniel

**Comment by jjscarafia** [comment]
El tema es que te falta un IVA en la factura, deberías agregarlo en las
líneas, igual l mensaje no es muy claro que digamos

**Comment by dbareiro** [comment]
Hola, Juan.

Gracias por responder. Estuve siguiendo estos pasos de un video que habías grabado [1] y ahí no introducías un IVA para la factura B. O al menos no daba este error al validar. ¿O me estoy perdiendo de algún paso?

Igual, ahora que lo vuelvo a ver con detenimiento, me parece que había un error en ese video porque más adelante [2] decís que "como es un consumidor final, no está discriminando IVA". Pero, si vemos la factura preimpresa, más abajo se ve que en realidad no aplicó en ningún momento el IVA a la factura. Puede ser que el problema pasara por ahí. Porque no le pusiste IVA y como no estaba haciendo alguna validación, imprimió la factura directamente sin IVA. Pero acá el error está siendo interceptado por esta validación que comentaba. ¿Puede ser?

Saludos,
Daniel

[1] https://youtu.be/99Ut_x98Dz0?t=650
[2] https://youtu.be/99Ut_x98Dz0?t=728

**Comment by jjscarafia** [comment]
La validación es nueva, puede ser que al momento del video no exitía.

**Comment by dbareiro** [comment]
Hola, Juan.

Perfecto. Gracias por la aclaración.

Saludos,
Daniel

**Comment by dbareiro** [comment]
Hola, Juan.

Veo que cerraste este ticket. ¿Hicieron algún cambio? ¿El detalle del mensaje, tal vez?

Saludos,
Daniel

**Comment by gabrielcz** [comment]
Hola, se podria omitir en algunos caso dicha validacion?

Gracias, saludos.

Gabriel
