### ISSUE TITLE
problema al validar factura de exportación

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/odoo-argentina#62]
Hola Juan
Tengo un problema cuando intento validar una factura de exportación en dolares, me dice:

> Warning:  Invoice subtotal (11.11) is different from invoice base vat amount (99.99)

Pareciera que está comparando el subtotal de la factura en USD con la base imponible en ARS

Tengo instalados los repos de adhoc en branch 8.0 y la imagen adhoc/odoo-adhoc:8.0

Para reproducirlo:
- tildar configuración contabilidad _Permitir multidivisa_
- ajustar tarifa USD a 0.111111
- crear un producto precio de venta 100
- crear cliente con lista de precios de compra y de venta en dolares, responsabilidad cliente del exterior, y una posición fiscal para mapear IVA 21% >> IVA 0%

![snap](https://cloud.githubusercontent.com/assets/8525908/9886855/ded9d4cc-5bc2-11e5-8fb7-c2ac9e98d675.png)

La verdad no se si realmente es un bug o estoy haciendo algo mal.
Saludos y gracias por anticipado.
Jorge Obiols

**Comment by jjscarafia** [comment]
Me parece que es un bug con redondeo, probá poner en configuración de
decimales a 3. Igualmente el mensaje es muy feo jeje, dejo anotado para
verlo

**Comment by jobiols** [comment]
hola Juan
Te hice el PR con un parche que estuve viendo, espero que lo veas bien porque es mi primera vez, un gusto colaborar...
Saludos!

**Comment by jjscarafia** [comment]
Cierro el issue por estar resolviendose en https://github.com/ingadhoc/odoo-argentina/pull/63
