### ISSUE TITLE
Validaciones factura en dolares

### ISSUE THREAD

**Issue by alejsouza** [ingadhoc/odoo-argentina#69]
Al momento de intentar validar una factura de exportación en doláres, el sistema muestra la siguiente validación 

Invoice ID: 35
Invoice subtotal (4800.00) is different from invoice base vat amount (44832.16) 

donde 4800 es el monto en doláres y 44832.16 es el monto es pesos. Al parecer hace la conversión de la moneda y compara los valores, lo cual causa que la comparación no de igual. Lo malo de esto es que la factura igual se manda a aprobar en AFIP, con lo cual queda registrada en AFIP pero no en odoo. Si la factura la hago en pesos no hay inconvenientes.

Gracias.-
Saludos.-

**Comment by jjscarafia** [comment]
De cuando es tu actualización? Fue arreglado en un commit de la última semana o la anterior.. Por favor confirmame para cerrar el issue

**Comment by alejsouza** [comment]
Bajé la ultima versión hoy, y seguia sin fucionar. Después de leer tu mensaje, reinicié el server y volví  a probar y funciona perfecto, se ve que algún cambio no lo estaba tomando. Por otro lado, algo que no es un issue... en la impresión de la factura en la leyenda del vencimiento figura fecha - Monto en pesos.

Gracias.-
