### ISSUE TITLE
Libro del partner en multidivisa

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/odoo-argentina#71]
Hola, Juan
Tengo el siguiente problema con odoo v8 Localización ADHOC, repo 8.0.x cuando quiero sacar el libro del partner en un ambiente multidivisa. Hice un ejemplo bien simple para que se entienda.

Tengo definido: Permitir multidivisa, Listas de precios cliente y proveedor en USD y además instalé  product_cost_currency product_price_currency y account_check

Creo un cliente Resp Inscripto, con tarifa de venta en USD
Le vendo un producto a USD 10 + IVA
Valido la factura y hago el pago.

Según veo los asientos contables están correctos, sin embargo cuando saco el libro del partner se ve la contabilidad en moneda local correctamente pero en la parte de moneda extranjera no contabiliza lo que hay en la columna debe. Esto pasa en ventas y también en compras.

Adjunto tres imágenes, Asientos de factura, Asientos pago y Libro del partner.

https://drive.google.com/open?id=0B1FiyKiZwx73bWg5RjhrVTRDNms
https://drive.google.com/open?id=0B1FiyKiZwx73anVUNHZfMTdnTW8
https://drive.google.com/open?id=0B1FiyKiZwx73akZLQldXaHNIa2c

Y un detalle más al agregar la tercer columna queda muy encimado el reporte tal vez seria bueno hacerlo apaisado.

Saludos.
Jorge

**Comment by jjscarafia** [comment]
Buenas Jorge, ese reporte es nativo de odoo y no está afectado por nada en nuestra localización.
Por lo que veo, la columna de la moneda extranjera no la termina totalizando pero si lo muestra correctamente (-12 y 12 respectivamente)
Podrías probar con los reportes de la OCA que pisan estos reportes
https://github.com/OCA/account-financial-reporting
a ver si lo tienen mejor resuelto. 
Cierro el issue porque no tiene que ver con esta localización

**Comment by jobiols** [comment]
Juan
Muchas gracias por el dato, seguiré buscando por ahi !
