### ISSUE TITLE
Signo menos dos veces en Reporte CITI Notas de Credito

### ISSUE THREAD

**Issue by aleibrecht** [ingadhoc/odoo-argentina#76]
Al computar los datos CITI y hay una nota de crédito, el txt que genera ademas de colocar el signo menos al inicio de la cadena de texto del numero (que esta correcto) ingresa otro cuando comienza el entero. te lo coloca de la forma 00300001000000000000000000010000000009995800005-0000000-209912 cuando tendria que ser 00300001000000000000000000010000000009995800005-00000000209912

En resumidas cuentas, tiene que ir solo un menos al inicio de los ceros y no al lado de los enteros.

**Comment by hsalomon** [comment]
En realidad también debe llevar el signo negativo en la base imponible, sería:
0030000100000000000000000001-0000000009995800005-00000000209912

Además se debe agregar el signo negativo en voucher_sale sino va a dar error al validar el aplicativo.

Comparto la respuesta porque lo uso en producción y siempre lo modifico a mano.

**Comment by jjscarafia** [comment]
Closed by https://github.com/ingadhoc/odoo-argentina/pull/92
