### ISSUE TITLE
Recibos

### ISSUE THREAD

**Issue by adrianpaesani** [ingadhoc/odoo-argentina#77]
Juan, una duda técnica, a lo mejor estoy perdido. Ahora en la actualización, cuando quiero hacer un recibo no me permite agregar distintos pagos para una operación (ej. Efectivo, Banco, Tarjeta), cosa que antes sí se podía. Para cada tipo de pago tengo que emitir varios recibos. Será que me falta instalar algo?. Muchas Gracias y perdón por generar un issue por esto.

**Comment by jjscarafia** [comment]
Adrian, dicha funcionalidad fue depreciada. Lo publicamos en el grupo de google y ahora también aquí.
http://www.odooargentina.com/blog/blog-1/post/modificaciones-en-repos-odoo-argentina-y-odoo-addons-de-adhoc-12#
Saludos!

**Comment by ivantodorovich** [comment]
> El módulo que agrega la posibilidad de múltiples medios de pago presentaba numerosas desventajas y conflictos con el modelo nativo de odoo, y es por esta razón que se procedió a su rediseño y mejora de arquitectura

¿Podrías elaborar en cuanto a los problemas que traía?

Tal vez podríamos contribuir a solucionarlo.
