### ISSUE TITLE
Problema al imprimir factura 

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#81]
Cuando se imprime la factura desde el botón imprimir factura la factura sale sin formato no así con el remito o con el presupuesto que salen bien, la base de datos tiene cargados los ejemplos.
Esto pasa sin usar factura electrónica, solamente la factura común
![imprimir factura](https://cloud.githubusercontent.com/assets/8353194/10624071/4a353f40-776b-11e5-9571-dc684ddf7f22.png)
![imprimir factura1](https://cloud.githubusercontent.com/assets/8353194/10624074/502135e4-776b-11e5-8a90-c7f054ded79e.png)

**Comment by gonzaloruzafa** [comment]
Esto es correcto, ya que aplica para pre impresos, como debe ser

Saludos!

**Comment by jjscarafia** [comment]
Exactamente, si mal no recuerdo, instalando factura electronica comienza a salir por defecto el reporte de factura electrónica.
