### ISSUE TITLE
Error al validar Factura Electrónica con conceptos No gravados y Exentos

### ISSUE THREAD

**Issue by hsalomon** [ingadhoc/odoo-argentina#82]
Al intentar validar facturas electrónicas con conceptos no gravados y exentos en las lineas de factura, arroja un error en AFIP:

10019: El campo Id en AlicIVA es obligatorio y debe ser alguno de los devueltos por el metodo FEParamGetTiposIva.

Las líneas de factura serían algo así:

producto A | precio unitario $ x.xx | impuesto IVA 21% | Importe $ x.xx
producto B | precio unitario $ x.xx | impuesto IVA Exento | Importe $ x.xx
producto C | precio unitario $ x.xx | impuesto IVA No Gravado | Importe $ x.xx

**Comment by jjscarafia** [comment]
DEberíras tener para cada impuesto configurado los códigos de impuestos correspondientes y estos codigos de impestos con todos los datos. Ej, iva ventas 21 con código iva ventas 21 con tipo "tax", impuesto "vat", aplicacion "nacional" y codigo afip 3, 4 o 5, no recuerdo bien cual.

Si instalas una bd con datos demo (o cualquiera de cero con el mod de plan contable) podes ver como esta confgurado por defecto. Podes verlo usando esta imagen de docker
http://www.odooargentina.com/page/instalar-con-docker-all-in-one

Cierro la incidencia salvo que haya más evidencia de que sea un bug

**Comment by hsalomon** [comment]
Instalé la imagen de docker con los datos demo, pero sucede lo mismo al cargar conceptos con IVA No gravado e IVA Exento 

AFIP Validation Error. 10048: El campo 'Importe Total' ImpTotal, debe ser igual a la suma de ImpTotConc + ImpNeto + ImpOpEx + ImpTrib + ImpIVA.
10019: El campo Id en AlicIVA es obligatorio y debe ser alguno de los devueltos por el metodo FEParamGetTiposIva.

![captura de pantalla de 2015-10-22 20 09 36](https://cloud.githubusercontent.com/assets/15252766/10698951/e3796a58-7989-11e5-8160-bb3ca3f27508.png)

Con respecto a la configuración de los códigos de impuesto, me da la sensación de que no pasa por ahí el problema, mas aún cuando los conceptos IVA No Gravado e IVA Exento no tienen código de alícuota Afip según la tabla (3 para IVA 0%, 4 para 10,5%, 5 para 21%, 6 para 27%, 8 para 5% y 9 para 2,5%), sino que creo yo que deberían tomarse como "imp_tot_conc" (Importe total de conceptos no gravados por el IVA) e "imp_op_ex (Importe de operaciones exentas).

Puede que esté totalmente errado porque la verdad que no sé nada de programación, pero la realidad es que no logro encontrar la manera de validar una factura que tenga IVA no Gravado e IVA Exento. Pido a quien esté interesado en el tema que haga la prueba de incluir en la línea de factura un producto y asignarle el IVA Exento o el IVA No gravado e intente validar la factura en AFIP.

Algo similar sucede al agregar percepciones en la factura.

![captura de pantalla de 2015-10-22 22 44 49](https://cloud.githubusercontent.com/assets/15252766/10698984/0ad38430-798a-11e5-9d5d-1eeb449e44c7.png)

Saludos y agradezco a quien me pueda orientar en el tema.

**Comment by srok** [comment]
Hola, tengo el mismo problema desde la imagen de docker. Si alguien encontró la solución por favor podría comentarla?

**Comment by 3lk0k0** [comment]
> Hola, tengo el mismo problema desde la imagen de docker. Si alguien encontró la solución por favor podría comentarla?

pudiste solucionarlo ?
