### ISSUE TITLE
2 directorios vacios

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#83]
l10n_ar_aeroo_receipt/i18n y l10n_ar_invoice_receipt/i18n están vacios... cuando será que vuelven a estar en linea?
Saludos

**Comment by gonzaloruzafa** [comment]
Noamix esas son las carpetas donde se alojan las traducciones, porque
registras como un issue que están vacíos?

**Comment by noamix** [comment]
mil disculpas gonzalo, se que suena raro 2 preguntas obvias seguidas pero estamos aprendiendo...ya me quedo claro que es de la traducción y en realidad preguntaba porque la inquietud me la paso un amigo que esta instalando y no se le instala el modulo Argentinian Aeroo Like Receipt Report... lo veo y le paso la respuesta ..cierro el issue y de nuevo mil disculpas.

**Comment by gonzaloruzafa** [comment]
No hay problema! Estamos a disposición!

**Comment by jjscarafia** [comment]
Esos dos módulos no existen mas y fueron reemplazados por otros
l10n_ar_aeroo_receipt==> l10n_ar_aeroo_voucher
l10n_ar_invoice_receipt ==>
l10n_ar_account_voucher

Saludos!
