### ISSUE TITLE
IVA Exento e IVA No Gravado

### ISSUE THREAD

**Issue by hsalomon** [ingadhoc/odoo-argentina#84]
Vuelvo a levantar el issue ya que no creo que sea una cuestión de configuración de códigos de impuestos a través de la interfaz de odoo.

Puntualmente al facturar un producto con IVA Exento, el valor debería ser tomado por la Factura Electronica con el parámetro "imp_op_ex" y no como alícuota de IVA con el parámetro "imp_iva"

Con respecto a facturar un producto con IVA No Gravado, el valor debería ser tomado por la Factura Electronica con el parámetro "imp_tot_conc" y no como alícuota de IVA con el parámetro "imp_iva"

Esto debido a que ni IVA Exento ni IVA No Gravado tienen código de alícuota de IVA.

Con respecto a otros impuestos que son agregados con el módulo Add Tax Importe de otros tributos (incluyendo percepciones de IVA, retenciones, IVA no inscripto, etc.) debería se tomado con el parámetro "imp_trib".

Creo que no está funcionando correctamente el módulo porque:

Cuando se factura con IVA Exento o IVA No Gravado, al pedir la validación de la factura electrónica, emite un error por el cual pide el código de alícuota en IVA "imp_iva" (lo cual no sería correcto ya que lo debería tomar como imp_op_ex o imp_tot_conc respectivamente).

Tener en cuenta que IVA 0% (que sí lleva el código de alícuota IVA "3") no es lo mismo que IVA Exento o IVA No Gravado.

Adjunto link con los parámetros de factura electrónica
http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#Descripci%C3%B3ndelaobtenci%C3%B3ndeCAECAEA

Si me equivoco, pido disculpas

**Comment by jjscarafia** [comment]
Claramente el iva exento, 0 y no grabado no son lo mismo, pero todos tienen codigos de afip y deben estar configurados para que el sistema funcione correctamente. Ver tabla afip.
Cierro incidencia, cualquier cosa volver a abrir

![image](https://cloud.githubusercontent.com/assets/3016656/10731671/40c72f7c-7bd5-11e5-8aeb-e61fc9857a61.png)

**Comment by hsalomon** [comment]
Juan entiendo claramente lo que me decís, pero si tenés la oportunidad de
realizar una prueba con la imagen de docker
http://www.odooargentina.com/page/instalar-con-docker-all-in-one, vas a ver
que no hay manera de facturar conceptos con IVA Exento o IVA no gravado con
la factura electrónica (la imagen de docker tiene solamente un punto
electrónico manual, hay que dar de alta el  punto de venta electrónico).

Agradezco tu respuesta, saludos
H.

**Comment by hsalomon** [comment]
Fijate en este ejemplo, al facturar con IVA No Gravado lo está tomando como ImpIVA cuando entiendo que lo debería tomar como imp_tot_conc

![captura de pantalla de 2015-10-26 14 21 18](https://cloud.githubusercontent.com/assets/15252766/10736690/1c5891ea-7bed-11e5-97cb-3609aa31d251.png)

Se entiende lo que trato de comentar?

**Comment by jjscarafia** [comment]
A bien, ya entiendo, si, la verdad es que ningún cliente nuestro hasta ahora factura conceptos no gravados que yo sepa, por eso no va a tener mucha prioridad para nuestro equipo esta incidencia pero cuando puedo la miro. Igualmente, siempre son bienvenidos los PR
Saludos, 
Juan

**Comment by hsalomon** [comment]
Me alegro que me hayas entendido, no se de programación pero deduzco que el problema está en cómo se captan los datos de la factura de odoo al momento de armar la info que se transmite al webservice.

De esta manera tanto el IVA Exento como el No Gravado se deben tomar como imp_op_ex o imp_tot_conc respectivamente y no como imp_iva.

No sé si estás líneas de código en invoice.py del módulo l10n_ar_afipws_fe tendrán que ver

# # invoice amount totals:

```
        imp_total = str("%.2f" % abs(inv.amount_total))
        imp_tot_conc = "0.00"
        imp_neto = str("%.2f" % abs(inv.amount_untaxed))
        imp_iva = str("%.2f" % abs(inv.vat_amount))
        imp_subtotal = imp_neto  # TODO: not allways the case!
        imp_trib = str("%.2f" % abs(inv.other_taxes_amount))
        imp_op_ex = str("%.2f" % abs(inv.vat_exempt_amount))
        moneda_id = inv.currency_id.afip_code
        moneda_ctz = inv.currency_rate
        # moneda_ctz = str(inv.company_id.currency_id.compute(
            # 1., inv.currency_id))
```

Si puedo ayudar en algo avisame

**Comment by jjscarafia** [comment]
Lamentablemente lo tuve en pendiente tratando de cerrar pero no llegué, me
estoy yendo de luna de miel y vuelvo en un mes. Al regreso lo encaramos.
Saludos!

**Comment by hsalomon** [comment]
Felicidades!!!!! que tengas una muy buena luna de miel.

Saludos
H.

**Comment by gabrielcz** [comment]
Me sumo a la issue, yo también requiero facturar cosas no gravadas...  
gracias.

**Comment by hsalomon** [comment]
¿Se pudo avanzar algo en el tema? ¿puedo aportar algo mas allá de lo que indiqué arriba?

gracias.

**Comment by jjscarafia** [comment]
La verdad me vengo postergando la tarea todas las semanas. Vengo muy a full
y la verdad que nadie lo requirió por ahora. Si algun cliente lo pide nos
va a apurar, si no lo tengo re en cuenta para ver.
De hecho estamos por empezar a trabajar en la v9 y vamos a reanalizar esta
parte..

**Comment by jjscarafia** [comment]
Arreglado para la v9, lo cierro

**Comment by 3lk0k0** [comment]
tengo el odoo v8, entonces no puedo facturar IVA exento ?
