### ISSUE TITLE
Faltan dígitos en los importes de precio en los reportes

### ISSUE THREAD

**Issue by noamix** [ingadhoc/odoo-argentina#88]
Si se fijan en la imagen el total no coincide con el subtotal

Configuración - Técnico  - Estructura de la base de datos - Precisión Decimal
Se cambio el valor Product Price de 2 que viene por defecto a 4 porque nuestros precios unitarios tienen el formato 0.9999 
En el ejemplo nuestro producto tiene el precio 0.4822
Pasa en todos los reportes creo, confirmado en Presupuestos - Facturas 
![captura de pantalla de 2015-11-03 13 03 29](https://cloud.githubusercontent.com/assets/8353194/10913453/b56e42fe-822c-11e5-9253-407f8e1eec51.png)

**Comment by jjscarafia** [comment]
Parecería ser algo del idioma porque en realidad dicho campo se imprime con  "<formatLang(line.printed_price_unit)>" y printed_price_unit toma cantidad de digtos del "Product Price", entonces quien lo estaría truncando sería  formatLang

Podes hacer algunas pruebas y volver con feedback? Si nos ayudas a detectar por donde o cual sería el cambio lo podemos resolver mas rápido

**Comment by noamix** [comment]
En estos días retomo este tema y veo que más puedo aportar...voy a ir probando en diferentes bases a ver que sale

**Comment by adrianpaesani** [comment]
Alguien logró solucionar este tema?

**Comment by adrianpaesani** [comment]
Encontré una solución, a este problema, modificando el formatLang del reporte del siguiente modo. Mi problema estaba en la cantidad de decimales para las cantidades, nosotros utilizamos 3, así que quedó de este modo:

`<formatLang(line.quantity,digits=3)>`

Me imagino que debe haber alguna forma de hacerlo programáticamente, pero todavía no lo probé.
Espero que les sirva.

**Comment by adrianpaesani** [comment]
Investigando un poco, creo que la solución sería la siguiente para que aparecieran correctamente los valores:
En el código algo así:
import openerp.addons.decimal_precision as dp

En los reportes (ya sea para el precio o para la unidad de medida):
`<formatLang(line.quantity,digits=dp.get_precision('Product` Price'))>
