### ISSUE TITLE
Error en generación de archivo para citi ventas

### ISSUE THREAD

**Issue by hsalomon** [ingadhoc/odoo-argentina#99]
El campo Cantidad de Alícuotas de IVA no puede ser cero para los comprobantes A y deberá ser igual a cero en el caso de los comprobantes B o C

Al registrar una factura de venta A con IVA Exento, sale "0" en cantidad de alícuotas cuando debería ser "1". A su vez no genera la línea de alicuota en el archivo Alicuots_sale_xx-xxxx.txt

este es la línea que sale, entre paréntesis está el valor que debería ser "1" y no "0"

201512310010009000000000000000002072                8000000000030111111113Pruebas Hnos. SRL             000000064800000000000000000000000000064800000000000000000000000000000000000000000000000000000000000000000000000000000000PES0001000000(0)E00000000000000000000000000000000000000000                              000000000000000

Estoy trabajando con localización argentina con el módulo Argentinian CITI Reports 8.0.1.1.0

**Comment by jjscarafia** [comment]
Arreglado con este commit https://github.com/ingadhoc/odoo-argentina/commit/0b969d4678bcb666cc5df56c3fab7be0a7928416

**Comment by hsalomon** [comment]
Buenísimo, gracias!!!

2016-03-21 16:57 GMT-03:00 Juan José Scarafía notifications@github.com:
